application: gemserkscores
version: 5
runtime: python
api_version: 1

handlers:

- url: /newGame
  login: admin
  script: application.py

- url: /updateScores
  login: admin
  script: application.py

- url: /.*
  script: application.py
