application: gemserkscores
version: 6
runtime: python
api_version: 1

handlers:

- url: /newGame
  login: admin
  script: application.py

- url: /updateScores
  login: admin
  script: application.py
  
- url: /removeDuplicatedDailyScores
  login: admin
  script: application.py

- url: /removeScoresForDay
  login: admin
  script: application.py
  
- url: /.*
  script: application.py
